### ISSUE TITLE
Installng database

### ISSUE THREAD

**Issue by oliver-moran** [future-analytics/reusingdublin#112]
Thanks a lot for doing this. It's great.

I'm in the process of setting up a version for Cork. Looks fine except the DB doesn't install (not tables). I hacked a bit until I ran `Site::install();` and that got me some bit of the way off the ground but there were still unknown columns (e.g. 'info' in 'field list').

Maybe the install script needs to be updated with more columns?

Thanks again.

**Comment by daithi-coombes** [comment]
hi @oliver-moran 

I have merged some changes in the master branch that should help with the installation process.

What is the exact error you are getting?

**Comment by edwardgalligan** [comment]
Hi Oliver, I tried using `Site::install();` myself and couldn't get it working as is so I wrote a separate independent install script: https://github.com/lucideer/reusingdublin/commit/ff45250b5e74fe3cca41cd064a81fe55be033981 - not sure if you've tried that.

See https://github.com/future-analytics/reusingdublin/issues/111

Note: Daithí is the author/maintainer; I'm just an interested party like yourself

**Comment by oliver-moran** [comment]
Thanks, guys.

Initially, I had no tables in the DB. So I dug around and saw `Site::install()`. So I thought it would be an idea to fire that. That did the trick until I got this:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'info' in 'field list'' in /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/lib/Model.php:73 Stack trace: #0 /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/lib/Model.php(73): PDOStatement->execute() #1 /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/lib/Site.php(409): ReusingDublin\Model->insert('Site', Array) #2 /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/lib/Site.php(211): ReusingDublin\Site->update(Array) #3 /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/lib/Controller.php(36): ReusingDublin\Site->actionEdit() #4 /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/index.php(31): ReusingDublin\Controller::factory(Array) #5 {main} thrown in /var/lib/openshift/56f529980c1e66da6e000106/app-root/runtime/repo/lib/Model.php on line 73 
```

Looks like the SQL script will solve that. Thanks a lot.

**Comment by daithi-coombes** [comment]
+1 to @lucideer for that sql script, thanks
